[package]
name = "examples"
version = "0.1.0"
authors = ["kydos <angelo@icorsaro.net>"]
publish = false
edition = "2018"

[dev-dependencies]
ddsc = { path = ".." }
libddsc-sys = { path = "../libddsc-sys" }
